name: Manual Build with Artifacts

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: octodash-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16'
      - name: Installing Dependencies
        run: npm ci
      - name: Building Application
        run: npm run build:prod
      - name: Packaging Application
        run: npm run electron:pack
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          path: package/octodash*.deb
